### ISSUE TITLE
Bot plays worse as White

### ISSUE THREAD

**Issue by healeycodes** [healeycodes/andoma#1]
The bot is stronger when playing as Black.

It appears to make blunders when playing as White that it shouldn't make per design.

**Comment by chitty** [comment]
Hey @healeycodes 

I started to work on [a fix for this](https://github.com/healeycodes/andoma/pull/3). I noticed that the `minimax_root` function was always being called with `is_maximising_player=True`. I also made some changes to consider favorable moves for white as positive integers and favorable moves for black as negative integers.

The bot plays better as white now, but there's still something off, specially in the endgame, the bot wouldn't do obvious checkmates, and the puzzle test is failing. I'll dig into that later.

Let me know what you think about this approach and if you have any suggestions.

Cheers.

**Comment by healeycodes** [comment]
Hi @chitty 

> I noticed that the `minimax_root` function was always being called with `is_maximising_player=True`

I think this was always initially called from the POV of the player we want to. So it's piece-color agnostic.

However, the changes you've made are great. Nice tests too!

> the bot wouldn't do obvious checkmates

I saw this at one point and couldn't get to the bottom of it. Some checkmates were fine but others weren't.

> Let me know what you think about this approach and if you have any suggestions.

The approach looks good. Can't think of any suggestions that might help re: checkmates.

<br>

Regarding this comment: `# This seem to be assuming that every capture is a trade`

This is only called when we're doing a cheap calculation to order moves before we search.

I think it implements this? https://www.chessprogramming.org/MVV-LVA
