### ISSUE TITLE
run command ?

### ISSUE THREAD

**Issue by tissatussa** [healeycodes/andoma#6]
i managed to let Andoma play in CuteChess by the command python ./main.py, however your documentation states the command python run ./main.py should execute the program :

python3: can't open file 'run': [Errno 2] No such file or directory

**Comment by healeycodes** [comment]
Thanks! I've fixed the README in https://github.com/healeycodes/andoma/commit/abe8973210e84c9d20d73675fbc3dbd4a2bea554
